

SOURCES := \
	util.ml \
	mapping.ml \
	test_mapping.ml \
	stringset.ml \
	celltype.ml \
	column.ml \
	heuristics.ml \
	main.ml

RESULT := os-mapgen
PACKS := csv str json-wheel
OCAMLFLAGS := -dtypes -warn-error Aez

include OCamlMakefile
